sudo: false
language: ruby

before_install:
  - gem update --system
  - gem install bundler
  - gem env

script:
  - cat $(bundle show metric_fu)/metric_fu.gemspec
  - bundle exec metric_fu

rvm:
  - 2.2.6
  - 2.3.3
